apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bobrgqls.devops.musala.com
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.Replicas
    description: The number of jobs launched
    name: Replicas
    type: integer
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: devops.musala.com
  names:
    kind: BobRGQL
    listKind: BobRGQLList
    plural: bobrgqls
    singular: bobrgql
  scope: Namespaced
  subresources:
    scale:
      labelSelectorPath: .status.LabelSelector
      specReplicasPath: .spec.Replicas
      statusReplicasPath: .status.Replicas
    status: {}
  validation:
    openAPIV3Schema:
      description: BobRGQL is the Schema for the bobrgqls API kubebuilder:printcolumn:name="Spec",type="integer",JSONPath=".spec.cronSpec",description="status
        of the kind"
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: BobRGQLSpec defines the desired state of BobRGQL
          properties:
            image:
              description: Image to deploy
              type: string
            replicas:
              description: Replicas that we need
              type: integer
          type: object
        status:
          description: BobRGQLStatus defines the observed state of BobRGQL
          properties:
            labelselector:
              type: string
            replicas:
              type: integer
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
