apiVersion: apps/v1
kind: Deployment
metadata:
  name: bobr-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bobr-operator
  template:
    metadata:
      labels:
        name: bobr-operator
    spec:
      serviceAccountName: bobr-operator
      containers:
        - name: bobr-operator
          # Replace this with the built image name
          image: dxas90/bobr-operator
          command:
          - bobr-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "bobr-operator"
